# Import libraries for visualization and numerical operations
import matplotlib as mpl
import matplotlib.pyplot as plt  # For plotting and displaying the maze
import numpy as np  # For array operations and image creation
from maze import Maze  # Custom Maze generator class
from maze_solver import solve_maze  # Function to solve the maze using pathfinding

class InteractiveMaze:
    """Interactive maze visualization with keyboard controls.
    This code was entirely generated by Claude """
    
    def __init__(self, maze_size=12):
        # Initialize game attributes
        self.maze_size = maze_size  # Size of the maze (e.g., 12x12)
        self.maze = None  # Will hold the generated Maze object
        self.current_position = None  # Player's current position in the maze
        self.goal_position = None  # Target position to reach
        self.path_history = []  # Track all positions visited by the player
        self.show_solution = False  # Flag to display the solution path
        self.solution_path = None  # Stores the computed solution path
        self.game_won = False  # Flag indicating if the goal has been reached
        
        # Set up the matplotlib figure and axis for visualization
        self.fig, self.ax = plt.subplots(figsize=(10, 10))
        # Connect keyboard events to the on_key_press handler
        self.fig.canvas.mpl_connect('key_press_event', self.on_key_press)
        
        # Generate the initial maze and set up the game
        self.new_maze()
        
    def new_maze(self):
        """Generate a new maze and reset game state."""
        # Create a new Maze object with the specified size
        self.maze = Maze(self.maze_size)
        # Convert start position from maze coordinates to display coordinates
        # (multiply by 2 and add 1 to center the player in the display grid)
        self.current_position = tuple(2 * x + 1 for x in self.maze.start_position)
        # Convert goal position using the same coordinate transformation
        self.goal_position = tuple(2 * x + 1 for x in self.maze.goal_position)
        # Initialize path history with the starting position
        self.path_history = [self.current_position]
        # Reset solution display flag
        self.show_solution = False
        # Compute the solution path for the new maze
        self.solution_path = solve_maze(self.maze)
        # Reset win condition
        self.game_won = False
        # Render the maze on screen
        self.draw_maze()
        
    def restart_maze(self):
        """Restart the current maze from the beginning."""
        # Reset player to the starting position
        self.current_position = tuple(2 * x + 1 for x in self.maze.start_position)
        # Clear the path history (don't count previous attempts)
        self.path_history = [self.current_position]
        # Hide the solution if it was displayed
        self.show_solution = False
        # Reset the win condition
        self.game_won = False
        # Redraw the maze
        self.draw_maze()
        
    def draw_maze(self):
        """Draw the maze with current position, goal, and optional solution."""
        # Clear any previous drawing
        self.ax.clear()
        
        if self.game_won:
            # Display victory screen when player reaches the goal
            self.ax.set_xlim(0, 10)
            self.ax.set_ylim(0, 10)
            self.ax.axis('off')
            
            # Show congratulations message
            self.ax.text(5, 7, 'CONGRATULATIONS!', 
                        ha='center', va='center', fontsize=24, 
                        color='green', weight='bold')
            # Display the number of moves taken (total steps minus starting position)
            self.ax.text(5, 6, f'You completed the maze in {len(self.path_history)-1} moves!',
                        ha='center', va='center', fontsize=14, color='black')
            
            # Display menu options for what to do next
            self.ax.text(5, 4.5, 'What would you like to do?',
                        ha='center', va='center', fontsize=16, weight='bold')
            self.ax.text(5, 3.5, 'R - Restart this maze',
                        ha='center', va='center', fontsize=14, color='blue')
            self.ax.text(5, 2.8, 'N - Start a new maze (same size)',
                        ha='center', va='center', fontsize=14, color='blue')
            self.ax.text(5, 2.1, 'C - Change maze size',
                        ha='center', va='center', fontsize=14, color='blue')
            self.ax.text(5, 1.4, 'Q - Quit',
                        ha='center', va='center', fontsize=14, color='blue')
        else:
            # Create an RGB image representation of the maze
            # Each cell in the maze will have a color: walls are black, corridors are white
            maze_display = np.ones(self.maze.shape + (3,))  # Create RGB array (white by default)
            maze_display[~self.maze.maze] = [0, 0, 0]  # Set walls to black
            
            # Draw the solution path first (so it appears under other colors)
            if self.show_solution and self.solution_path:
                for pos in self.solution_path:
                    maze_display[pos] = [0.7, 0.7, 1.0]  # Light blue for solution path
            
            # Draw the player's visited path on top of solution (all positions except current)
            for pos in self.path_history[:-1]:
                maze_display[pos] = [1, 1, 0]  # Yellow for visited path
            
            # Draw the goal position in green (on top of visited path)
            goal_x, goal_y = self.goal_position
            maze_display[goal_x, goal_y] = [0, 1, 0]  # Green for goal
            
            # Draw the player's current position in red (on top of everything)
            curr_x, curr_y = self.current_position
            maze_display[curr_x, curr_y] = [1, 0, 0]  # Red for current player position
            
            # Display the colored maze image on screen
            self.ax.imshow(maze_display, interpolation='nearest')
            # Create title showing current game status and control instructions
            # Shows maze size, number of moves taken, and control key reminders
            self.ax.set_title(f'Interactive Maze (Size: {self.maze_size}) - Moves: {len(self.path_history)-1}\n' +
                             'Arrow keys to move | T: toggle solution | R: restart | N: new maze | C: change size | Q: quit',
                             fontsize=10)
            # Hide axis labels and ticks for cleaner appearance
            self.ax.axis('off')
        
        # Update the canvas display
    
    def on_key_press(self, event):
        """Handle keyboard input for maze navigation."""
        # Check if game is already won
        if self.game_won:
            # Handle options on the victory screen
            if event.key == 'r':
                self.restart_maze()  # Restart the current maze
            elif event.key == 'n':
                self.new_maze()  # Generate a new maze of the same size
            elif event.key == 'c':
                self.change_size()  # Prompt user to change maze size
            elif event.key == 'q':
                plt.close(self.fig)  # Close the game window
            return
        
        # Process game controls during active gameplay
        moved = False  # Track whether the player successfully moved
        
        # Handle arrow key movements (move player one cell in direction)
        if event.key == 'up':
            new_pos = (self.current_position[0] - 1, self.current_position[1])  # Move up
            moved = self.try_move(new_pos)
        elif event.key == 'down':
            new_pos = (self.current_position[0] + 1, self.current_position[1])  # Move down
            moved = self.try_move(new_pos)
        elif event.key == 'left':
            new_pos = (self.current_position[0], self.current_position[1] - 1)  # Move left
            moved = self.try_move(new_pos)
        elif event.key == 'right':
            new_pos = (self.current_position[0], self.current_position[1] + 1)  # Move right
            moved = self.try_move(new_pos)
        
        # Toggle between showing and hiding the solution path
        elif event.key == 't':
            self.show_solution = not self.show_solution
            self.draw_maze()
            return
        
        # Restart the maze from the starting position
        elif event.key == 'r':
            self.restart_maze()
            return
        
        # Generate a new maze with the same size
        elif event.key == 'n':
            self.new_maze()
            return
        
        # Prompt user to change the maze size
        elif event.key == 'c':
            self.change_size()
            return
        
        # Quit the game
        elif event.key == 'q':
            plt.close(self.fig)
            return
        
        # Redraw the maze if the player successfully moved
        if moved:
            # Check if the player has reached the goal
            if self.current_position == self.goal_position:
                self.game_won = True  # Set win condition to true
            self.draw_maze()  # Update the display
    
    def try_move(self, new_pos):
        """Attempt to move to a new position. Returns True if successful."""
        # Verify the new position is within the maze boundaries
        if (0 <= new_pos[0] < self.maze.shape[0] and 
            0 <= new_pos[1] < self.maze.shape[1]):
            
            # Check if the new position is a floor cell (not a wall)
            # maze.maze[pos] is True for floors and False for walls
            if self.maze.maze[new_pos]:
                # Update player position
                self.current_position = new_pos
                # Record this move in the path history
                self.path_history.append(new_pos)
                return True  # Movement was successful
        
        return False  # Movement failed (out of bounds or hit a wall)
    
    def change_size(self):
        """Prompt user to change maze size and recreate the game with new settings."""
        # Close the current game window
        plt.close(self.fig)
        
        # Display size change menu
        print("\n" + "="*50)
        print("CHANGE MAZE SIZE")
        print("="*50)
        # Get the new maze size from the user
        new_size = get_maze_size()
        
        # Update the maze size setting
        self.maze_size = new_size
        # Create a new figure and axis for the game window
        self.fig, self.ax = plt.subplots(figsize=(10, 10))
        # Connect keyboard handler to the new figure
        self.fig.canvas.mpl_connect('key_press_event', self.on_key_press)
        # Generate a new maze with the new size
        self.new_maze()
        # Display the new maze
        plt.show()
    
    def show(self):
        """Display the interactive maze game window."""
        # Show the matplotlib figure (blocks until window is closed)
        plt.show()


def get_maze_size():
    """Prompt user for maze size with validation and recommendations."""
    while True:  # Keep asking until valid input is received
        try:
            print("\nEnter maze size (recommended: 5-20):")
            # Show size recommendations
            print("  - Small (5-8): Quick and easy")
            print("  - Medium (9-15): Balanced challenge")
            print("  - Large (16-25): Complex and time-consuming")
            print("  - Very Large (26+): For the brave!")
            
            # Get input from user and convert to integer
            size = int(input("\nMaze size: "))
            
            # Validate minimum size (must be at least 3x3)
            if size < 3:
                print("❌ Size must be at least 3. Please try again.")
                continue
            # Warn about very large sizes and ask for confirmation
            elif size > 50:
                print("⚠️  Warning: Size > 50 may be slow to generate and difficult to navigate.")
                confirm = input("Continue anyway? (y/n): ").lower()
                if confirm != 'y':
                    continue  # Ask for size again if user doesn't confirm
            
            return size  # Return valid size
            
        except ValueError:
            # Handle non-integer input
            print("❌ Invalid input. Please enter a number.")
        except KeyboardInterrupt:
            # Handle Ctrl+C gracefully
            print("\n\nExiting...")
            exit(0)


def visualize_maze(maze, interactive=True):
    """
    Visualize a maze in either interactive or static mode.
    
    Args:
        maze: Maze object to visualize
        interactive: If True, create playable interactive version. If False, display static maze.
    """
    if interactive:
        # Create an interactive game with the provided maze
        interactive_maze = InteractiveMaze(maze_size=8)
        # Replace the generated maze with the provided one
        interactive_maze.maze = maze
        # Set start position using coordinate transformation
        interactive_maze.current_position = tuple(2 * x + 1 for x in maze.start_position)
        # Set goal position using coordinate transformation
        interactive_maze.goal_position = tuple(2 * x + 1 for x in maze.goal_position)
        # Initialize path starting from the start position
        interactive_maze.path_history = [interactive_maze.current_position]
        # Compute the solution path for this maze
        interactive_maze.solution_path = solve_maze(maze)
        # Draw the maze on screen
        interactive_maze.draw_maze()
        # Display the interactive game
        interactive_maze.show()
    else:
        # Create a static (non-playable) visualization of the maze
        fig, ax = plt.subplots(figsize=(10, 10))
        
        # Create RGB image with white backgrounds
        maze_display = np.ones(maze.shape + (3,))
        # Color walls black
        maze_display[~maze.maze] = [0, 0, 0]  # Black for walls
        
        # Mark the start position and goal position on the display
        start = tuple(2 * x + 1 for x in maze.start_position)
        goal = tuple(2 * x + 1 for x in maze.goal_position)
        maze_display[start[0], start[1]] = [1, 0, 0]  # Red for start
        maze_display[goal[0], goal[1]] = [0, 1, 0]  # Green for goal
        
        # Display the maze image
        ax.imshow(maze_display, interpolation='nearest')
        ax.set_title('Maze (Red=Start, Green=Goal)', fontsize=14)
        ax.axis('off')
        # Show the figure
        plt.show()


if __name__ == "__main__":
    # Entry point of the program - runs when this script is executed directly
    print("=" * 60)
    print("INTERACTIVE MAZE GAME")
    print("=" * 60)
    
    # Prompt user to choose the maze size
    maze_size = get_maze_size()
    
    print(f"\nGenerating {maze_size}×{maze_size} maze...")
    
    # Display game instructions
    print("\nLaunching interactive maze...")
    print("\nControls:")
    print("  Arrow keys - Move through the maze")
    print("  T - Toggle solution display")
    print("  R - Restart current maze")
    print("  N - Generate new maze (same size)")
    print("  C - Change maze size")
    print("  Q - Quit")
    print("\nGoal: Navigate from the red cell to the green cell!")
    
    # Create and start the interactive maze game
    interactive_maze = InteractiveMaze(maze_size=maze_size)
    # Display the game window
    interactive_maze.show()