import numpy as np  
from collections import deque  
from maze import Maze 

def solve_maze(maze):
    """
    Solve the maze using Breadth-First Search (BFS) algorithm.
    
    BFS is ideal for finding the shortest path in an unweighted grid.
    It explores all neighbors at the current distance before moving to further distances.
    
    Args:
        maze: Maze object to solve
        
    Returns:
        list of tuples: Path from start to goal position (each tuple is a cell coordinate),
                       or None if no solution exists

    This code was entirely generated by Claude 
    """
    # Convert maze start position from internal coordinates to display coordinates
    # (start_position is at maze indices, need to multiply by 2 and add 1 for display grid)
    start = tuple(2 * x + 1 for x in maze.start_position)
    # Similarly, convert the goal position
    goal = tuple(2 * x + 1 for x in maze.goal_position)
    
    # Initialize BFS queue with tuples containing: (current_position, path_to_position)
    # The path includes all positions visited from start to current position
    queue = deque([(start, [start])])  
    # Track visited positions to avoid revisiting the same cell (prevents infinite loops)
    visited = set([start])
    
    # Define the four cardinal directions for movement: up, down, left, right
    # Each tuple represents (row_change, column_change)
    directions = [(-1, 0), (1, 0), (0, -1), (0, 1)]
    
    # Continue exploring until the queue is empty
    while queue:
        # Dequeue the next position to explore (FIFO - first in, first out)
        current_pos, path = queue.popleft()
        
        # Check if we have reached the goal position
        if current_pos == goal:
            # Return the complete path from start to goal
            return path
        
        # Explore all four neighboring cells from the current position
        for dx, dy in directions:
            # Calculate the position of the neighbor cell
            next_pos = (current_pos[0] + dx, current_pos[1] + dy)
            
            # Verify the neighbor is within the maze boundaries (not out of bounds)
            if (0 <= next_pos[0] < maze.shape[0] and 
                0 <= next_pos[1] < maze.shape[1]):
                
                # Check if the neighbor is a walkable floor (not a wall) and hasn't been visited
                # maze.maze[next_pos] is True for floors, False for walls
                if maze.maze[next_pos] and next_pos not in visited:
                    # Mark this position as visited
                    visited.add(next_pos)
                    # Add the neighbor to the queue with the extended path
                    # path + [next_pos] creates a new list with the neighbor appended
                    queue.append((next_pos, path + [next_pos]))
    
    # If we exit the while loop without finding the goal, no solution exists
    return None  # No solution found


if __name__ == "__main__":
    # This code only runs when the script is executed directly (not imported)
    
    # Create a test maze with size 8x8
    m = Maze(8)
    # Display the maze using the maze's built-in display method
    m.display()
    
    # Attempt to solve the maze using our BFS algorithm
    solution = solve_maze(m)
    # Check if a solution path was found
    if solution:
        # Display the solution path length (number of cells in the path)
        print(f"\nSolution found! Path length: {len(solution)}")
        # Show the first few steps of the path as a preview
        print(f"First few steps: {solution[:5]}")
    else:
        # If no solution was found, notify the user
        print("\nNo solution found!")
